### ISSUE TITLE
Broken devcontainer CI

### ISSUE THREAD

**Issue by kachick** [kachick/wait-other-jobs#551]
- Scheduled CI failed, retrying does not fix it - https://github.com/kachick/wait-other-jobs/actions/runs/5687394320
- Actually works in local

```
  
  Error: Command failed: /bin/sh -c ./.devcontainer/bootstrap.bash
      at YY (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:235:130)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Rl (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:4396)
      at async yl (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:3741)
      at async Sl (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:2945)
      at async Js (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:2389)
      at async sAA (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:462:1346)
      at async mK (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:462:964)
      at async mAA (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:479:3660)
      at async LC (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:479:4775)
  
  Error: Dev container up failed: Command failed: /bin/sh -c ./.devcontainer/bootstrap.bash (exit code: undefined)
  The postCreateCommand in the devcontainer.json failed.
  Error: Command failed: /bin/sh -c ./.devcontainer/bootstrap.bash
```

Looks related to https://github.com/devcontainers/cli/issues/606, https://github.com/devcontainers/ci/pull/253

**Comment by kachick** [comment]
Fixed in current main without any changes in our code


https://github.com/kachick/wait-other-jobs/actions/runs/5695116872
